= osx-bootstrap
:toc:
:toc-placement!:

Script to set up a Mac OS X

It can be run multiple times on the same machine safely. It installs, upgrades, or skips packages based on what is already installed on the machine.

toc::[]

== Requirements
Shell::
* http://zsh.sourceforge.net[z shell]
* https://www.gnu.org/software/bash[bash]

Operating System::
* OS X >= 10.10 

== What it sets up
Mac OS X tools::
* http://brew.sh/[Homebrew] for managing operating system libraries.
Unix tools::
* https://git-scm.com[Git] for version control
* https://www.openssl.org[OpenSSL] for Transport Layer Security (TLS)

== Install
Clone, review, then execute the script:

[source,bash]
-----
sh bootstrap
-----

To install with samples provided in the repo run

[source,bash]
-----
sh bootstrap sample
-----

== Customize
Customize in 
* `~/.bootstrap.local`
* `~/.Brewfile`

These files are left in place and can be edited locally for further customization.

=== Local Brewfile

A https://github.com/Homebrew/homebrew-bundle[Brewfile] is like a Gemfile for non-ruby dependencies. Anything you would install via http://brew.sh/[homebrew] you can drop into your `~/.Brewfile` and it will be installed during the bootstrap script.

An example Brewfile looks like this:
[source,ruby]
-----
# 3rd party Taps
tap 'homebrew/bundle'
tap 'caskroom/cask'

# Homebrew Packages
brew 'ack'
brew 'keybase'
brew 'tmux'

# Cask macOS Apps
cask 'java'

# Mac store Apps
mas '1Password', id: 443987910
mas 'Xcode', id: 497799835
-----

=== bootstrap.local

Your `bootstrap.local` is run at the end of the bootstrap script.
Put your customizations there.
An example local script could look like this:

[source,bash]
-----
#!/bin/bash
...
echo "Add your changes here"
...
-----

Write your customizations such that they can be run safely more than once.
See the `bootstrap` script for examples.

Script functions such as `append_to_shellrc`, `fancy_echo` and `install_or_update_gem` can be used in your `~/.bootstrap.local`.

